package com.kyrincloud.MysqlSharding;

import java.io.InputStream;
import java.io.Reader;
import java.io.Serializable;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;

public abstract class AbstractShardingPreparedStatmentWrapper implements PreparedStatement,Serializable {

	public void addBatch(String sql) throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support addBatch");
	}

	public void cancel() throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support cancel");
	}

	public void clearBatch() throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support clearBatch");
	}

	public void clearWarnings() throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support clearWarnings");
	}

	public void close() throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support close");
	}

	public void closeOnCompletion() throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support closeOnCompletion");
	}

	public abstract boolean execute(String sql, int autoGeneratedKeys) throws SQLException;

	public abstract boolean execute(String sql, int[] columnIndexes) throws SQLException;

	public abstract boolean execute(String sql, String[] columnNames) throws SQLException;

	public abstract boolean execute(String sql) throws SQLException;

	public int[] executeBatch() throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support executeBatch");
	}

	public abstract ResultSet executeQuery(String sql) throws SQLException;

	public abstract int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException;

	public abstract int executeUpdate(String sql, int[] columnIndexes) throws SQLException;

	public abstract int executeUpdate(String sql, String[] columnNames) throws SQLException;

	public abstract int executeUpdate(String sql) throws SQLException;

	public abstract Connection getConnection() throws SQLException;

	public int getFetchDirection() throws SQLException {
		 throw new SQLFeatureNotSupportedException(" not support closeOnCompletion");
	}

	public int getFetchSize() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public ResultSet getGeneratedKeys() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public int getMaxFieldSize() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public int getMaxRows() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public boolean getMoreResults() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public boolean getMoreResults(int current) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public int getQueryTimeout() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public ResultSet getResultSet() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public int getResultSetConcurrency() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public int getResultSetHoldability() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public int getResultSetType() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public int getUpdateCount() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public SQLWarning getWarnings() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public boolean isCloseOnCompletion() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public boolean isClosed() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public boolean isPoolable() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setCursorName(String name) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setEscapeProcessing(boolean enable) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setFetchDirection(int direction) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setFetchSize(int rows) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setMaxFieldSize(int max) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setMaxRows(int max) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setPoolable(boolean poolable) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setQueryTimeout(int seconds) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void addBatch() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void clearParameters() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public abstract boolean execute() throws SQLException;

	public abstract ResultSet executeQuery() throws SQLException;

	public abstract int executeUpdate() throws SQLException;

	public ResultSetMetaData getMetaData() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public ParameterMetaData getParameterMetaData() throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setArray(int parameterIndex, Array x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBlob(int parameterIndex, Blob x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBoolean(int parameterIndex, boolean x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setByte(int parameterIndex, byte x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setBytes(int parameterIndex, byte[] x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setClob(int parameterIndex, Clob x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setClob(int parameterIndex, Reader reader) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setDate(int parameterIndex, Date x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setDouble(int parameterIndex, double x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setFloat(int parameterIndex, float x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setInt(int parameterIndex, int x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setLong(int parameterIndex, long x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNClob(int parameterIndex, NClob value) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNClob(int parameterIndex, Reader reader) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNString(int parameterIndex, String value) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setNull(int parameterIndex, int sqlType) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
		 throw new SQLFeatureNotSupportedException();

	}

	public void setObject(int parameterIndex, Object x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();

	}

	public void setRef(int parameterIndex, Ref x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setRowId(int parameterIndex, RowId x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setShort(int parameterIndex, short x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setString(int parameterIndex, String x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setTime(int parameterIndex, Time x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setURL(int parameterIndex, URL x) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

	public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
		 throw new SQLFeatureNotSupportedException();
	}

}
