package com.kyrincloud.MysqlSharding;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ShardingConnection extends AbstractShardingConnectionWrapper {

	
	private List<Connection> connections;
	
	
	public ShardingConnection(List<Connection> connections) {
		this.connections=connections;
	}

	@Override
	public Statement createStatement() throws SQLException {
		System.out.println("---createStatement 1---");
		return null;
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		System.out.println("---createStatement 2---");
		throw new SQLException("not support createStatement");
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		System.out.println("---createStatement 3---");
		throw new SQLException("not support createStatement");
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		System.out.println("---prepareStatement 1---");
		return new ShardingPreparedStatment(createPs(sql));
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
			throws SQLException {
		System.out.println("---prepareStatement 2---");
		return new ShardingPreparedStatment(createPs(sql));
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		System.out.println("---prepareStatement 3---");
		return new ShardingPreparedStatment(createPs(sql));
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		System.out.println("---prepareStatement 4---");
		return new ShardingPreparedStatment(createPs(sql));
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		System.out.println("---prepareStatement 5---");
		return new ShardingPreparedStatment(createPs(sql));
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		System.out.println("---prepareStatement 6---");
		return new ShardingPreparedStatment(createPs(sql));
	}
	
	public List<Connection> getConnections(){
		return this.connections;
	}
	
	private List<PreparedStatement> createPs(String sql) throws SQLException{
		List<PreparedStatement> list=new ArrayList<PreparedStatement>();
		for(Connection conn:connections){
			list.add(conn.prepareStatement(sql));
		}
		return list;
	}
	
}
